### ISSUE TITLE
Darcula Package doesn't exist

### ISSUE THREAD

**Issue by angelsflyinhell** [angelsflyinhell/XAnime#4]
Branch: gui

```
XAnime\src\main\java\Gui\GUI.java:4:28
java: package com.bulenkov.darcula does not exist
```
Fix by using an imported version per Maven

**Comment by Nilstrieb** [comment]
works on my machine

**Comment by Nilstrieb** [comment]
oh right you need the .jar fuck I hate maven

**Comment by Nilstrieb** [comment]
Wait you fixed it with maven wtf

**Comment by angelsflyinhell** [comment]
you should include the jar in the build, that should fix it

**Comment by Nilstrieb** [comment]
fixed with new library that supports Darcula and is on maven
